# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: create-mg
variables:
  - name: buildType
    value: deploy
  - name: yourResourceGroup
    value: manishResourceGroup
  - name: AzureCloudServiceConnection
    value: AzureServiceConnection@mg-s-mg
  - name: location
    value: "West US"
  - name: csmFileVar
    value: azuredeploy.json
  - name: csmParametersFileVar
    value: azuredeploy.parameters.json
  - name: workingDirectory
    value: management-level-deployment

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - management-level-deployment 

pool:
  vmImage: 'windows-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection@TenantRootGroup'
    scriptType: 'batch'
    scriptLocation: 'scriptPath'
    scriptPath: '${{ variables.workingDirectory }}/4.create-policy.bat'
    arguments: '${{ variables.workingDirectory }} ${{ variables.csmFileVar }} ${{ variables.csmParametersFileVar }}'
    useGlobalConfig: false

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection@TenantRootGroup'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment mg create --name demoMGDeployment --location WestUS --management-group-id mg-s-mg --template-file azuredeploy.json --parameters @azuredeploy.parameters.json'
    arguments: 'temp'
    useGlobalConfig: false
    workingDirectory: '${{ variables.workingDirectory }}'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Management Group'
    azureResourceManagerConnection: '${{ variables.AzureServiceConnection}}'
    location: '${{ variables.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '${{ variables.workingDirectory }}/${{ variables.csmFileVar }}'
    csmParametersFile: '${{ variables.workingDirectory }}/${{ variables.csmParametersFileVar }}'
    deploymentMode: 'Incremental'
    deploymentName: 'Deploys-ManagementGroups'
    deploymentOutputs: 'OutputsFromDeployment'
    addSpnToEnvironment: false

- task: ARM Outputs@6
  condition: eq('${{ variables.buildType }}', 'deploy')
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: '${{ variables.AzureCloudServiceConnection }}'
    resourceGroupName: '${{ variables.yourResourceGroup }}'
    whenLastDeploymentIsFailed: 'fail'

- task: AzureCLI@2
  condition: eq('${{ variables.buildType }}', 'destroy')
  inputs:
    azureSubscription: '${{ variables.AzureCloudServiceConnection }}'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group delete --yes --resource-group %1'
    arguments: '${{ variables.yourResourceGroup }}'
- task: BatchScript@1
  condition: eq('${{ variables.buildType }}', 'destroy')
  inputs:
    filename: 'putInfoOnCommit.bat'
    arguments: '\"All resources destroyed for $(yourResourceGroup)\"'